# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"

# https://devblogs.microsoft.com/dotnet/using-dependabot-to-manage-dotnet-sdk-updates/
#  - package-ecosystem: "dotnet-sdk"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#      day: "wednesday"
#    ignore:
#      - dependency-name: "*"
#        update-types: 
#          - "version-update:semver-major"
#          - "version-update:semver-minor"
